-- Migration: Rename measurements to station_measurements and create weather_measurements table
-- This migration separates raw monitoring data from weather data

-- Step 1: Rename measurements table to station_measurements
ALTER TABLE IF EXISTS "public"."measurements" RENAME TO "station_measurements";

-- Update the sequence name to match the new table name
ALTER SEQUENCE IF EXISTS "public"."measurements_id_seq" RENAME TO "station_measurements_id_seq";

-- Update foreign key constraint name for clarity (optional but cleaner)
ALTER TABLE IF EXISTS "public"."station_measurements" 
  DROP CONSTRAINT IF EXISTS "measurements_station_id_fkey";

ALTER TABLE IF EXISTS "public"."station_measurements"
  ADD CONSTRAINT "station_measurements_station_id_fkey" 
  FOREIGN KEY (station_id) REFERENCES public.stations (id) ON DELETE CASCADE;

-- Update unique constraint name
ALTER TABLE IF EXISTS "public"."station_measurements"
  DROP CONSTRAINT IF EXISTS "measurements_station_id_measured_at_key";

ALTER TABLE IF EXISTS "public"."station_measurements"
  ADD CONSTRAINT "station_measurements_station_id_measured_at_key" 
  UNIQUE (station_id, measured_at);

-- Update check constraints names
ALTER TABLE IF EXISTS "public"."station_measurements"
  DROP CONSTRAINT IF EXISTS "measurements_source_check";

ALTER TABLE IF EXISTS "public"."station_measurements"
  ADD CONSTRAINT "station_measurements_source_check" 
  CHECK (source = ANY (ARRAY['manual'::text, 'automated'::text]));

ALTER TABLE IF EXISTS "public"."station_measurements"
  DROP CONSTRAINT IF EXISTS "measurements_status_check";

ALTER TABLE IF EXISTS "public"."station_measurements"
  ADD CONSTRAINT "station_measurements_status_check" 
  CHECK (status = ANY (ARRAY['verified'::text, 'pending'::text, 'rejected'::text]));

-- Update index names
ALTER INDEX IF EXISTS "idx_measurements_station" RENAME TO "idx_station_measurements_station";
ALTER INDEX IF EXISTS "idx_measurements_time" RENAME TO "idx_station_measurements_time";

-- Drop old RLS policies and create new ones with updated names
DROP POLICY IF EXISTS "Allow public read access" ON "public"."station_measurements";
DROP POLICY IF EXISTS "Allow admin select" ON "public"."station_measurements";
DROP POLICY IF EXISTS "Allow admin insert" ON "public"."station_measurements";
DROP POLICY IF EXISTS "Allow admin update" ON "public"."station_measurements";
DROP POLICY IF EXISTS "Allow admin delete" ON "public"."station_measurements";

CREATE POLICY "Allow public read access" ON "public"."station_measurements" 
  FOR SELECT USING (true);

CREATE POLICY "Allow admin insert" ON "public"."station_measurements" 
  FOR INSERT TO public 
  WITH CHECK (public.authorize('data.manage'::public.app_permission, auth.uid()));

CREATE POLICY "Allow admin update" ON "public"."station_measurements" 
  FOR UPDATE TO public 
  USING (public.authorize('data.manage'::public.app_permission, auth.uid()))
  WITH CHECK (public.authorize('data.manage'::public.app_permission, auth.uid()));

CREATE POLICY "Allow admin delete" ON "public"."station_measurements" 
  FOR DELETE TO public 
  USING (public.authorize('data.manage'::public.app_permission, auth.uid()));

-- Step 2: Create weather_measurements table
CREATE TABLE IF NOT EXISTS "public"."weather_measurements" (
    "id" bigint NOT NULL,
    "station_id" bigint NOT NULL,
    "measured_at" timestamp with time zone NOT NULL,
    "temperature" numeric,           -- Temperature in Celsius (converted from Kelvin)
    "temp_min" numeric,              -- Min temperature in Celsius
    "temp_max" numeric,              -- Max temperature in Celsius
    "feels_like" numeric,            -- Feels like temperature in Celsius
    "pressure" numeric,              -- Atmospheric pressure in hPa
    "humidity" numeric,              -- Humidity percentage
    "wind_speed" numeric,            -- Wind speed in m/s
    "wind_deg" numeric,              -- Wind direction in degrees
    "rain_1h" numeric,               -- Rain volume for last 1 hour in mm
    "clouds" numeric,                -- Cloudiness percentage
    "visibility" numeric,            -- Visibility in meters
    "weather_main" text,             -- Weather condition (e.g., "Rain", "Clear")
    "weather_description" text,      -- Weather description (e.g., "moderate rain")
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT "weather_measurements_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "public"."weather_measurements" OWNER TO "postgres";

COMMENT ON TABLE "public"."weather_measurements" IS 'Weather data from OpenWeather API for each monitoring station.';

-- Add auto-increment for id
ALTER TABLE "public"."weather_measurements"
ALTER COLUMN "id"
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."weather_measurements_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- Add foreign key constraint
ALTER TABLE "public"."weather_measurements"
  ADD CONSTRAINT "weather_measurements_station_id_fkey" 
  FOREIGN KEY (station_id) REFERENCES public.stations (id) ON DELETE CASCADE;

-- Add unique constraint for station_id + measured_at
ALTER TABLE "public"."weather_measurements"
  ADD CONSTRAINT "weather_measurements_station_id_measured_at_key" 
  UNIQUE (station_id, measured_at);

-- Create indexes for performance
CREATE INDEX "idx_weather_measurements_station" ON "public"."weather_measurements" USING btree (station_id);
CREATE INDEX "idx_weather_measurements_time" ON "public"."weather_measurements" USING btree (measured_at);

-- Enable RLS
ALTER TABLE "public"."weather_measurements" ENABLE ROW LEVEL SECURITY;

-- RLS Policies for weather_measurements
CREATE POLICY "Allow public read access" ON "public"."weather_measurements" 
  FOR SELECT USING (true);

CREATE POLICY "Allow admin insert" ON "public"."weather_measurements" 
  FOR INSERT TO public 
  WITH CHECK (public.authorize('data.manage'::public.app_permission, auth.uid()));

CREATE POLICY "Allow admin update" ON "public"."weather_measurements" 
  FOR UPDATE TO public 
  USING (public.authorize('data.manage'::public.app_permission, auth.uid()))
  WITH CHECK (public.authorize('data.manage'::public.app_permission, auth.uid()));

CREATE POLICY "Allow admin delete" ON "public"."weather_measurements" 
  FOR DELETE TO public 
  USING (public.authorize('data.manage'::public.app_permission, auth.uid()));

-- Grant permissions
GRANT ALL ON TABLE "public"."weather_measurements" TO "anon";
GRANT ALL ON TABLE "public"."weather_measurements" TO "authenticated";
GRANT ALL ON TABLE "public"."weather_measurements" TO "service_role";
GRANT ALL ON SEQUENCE "public"."weather_measurements_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."weather_measurements_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."weather_measurements_id_seq" TO "service_role";

-- Step 3: Add hourly cron job for sync-weather Edge Function
-- Note: The actual cron job needs to be configured via Supabase Dashboard or with actual project credentials
-- SELECT cron.schedule(
--   'sync-weather-hourly',
--   '0 * * * *',  -- Every hour at minute 0
--   $$
--   SELECT net.http_post(
--     url := 'https://YOUR_PROJECT_REF.supabase.co/functions/v1/sync-weather',
--     headers := jsonb_build_object(
--       'Authorization', 'Bearer YOUR_SERVICE_ROLE_KEY',
--       'Content-Type', 'application/json'
--     ),
--     body := '{}'::jsonb
--   ) AS request_id;
--   $$
-- );
